# Left thumb stick
axis_linear:
  x: 1
  y: 0
scale_linear:
  x: 1.0
  y: 1.0
scale_linear_turbo:
  x: 2.0
  y: 2.0

# Right thumb stick
axis_angular:
  yaw: 2
scale_angular:
  yaw: 1.5

# Left trigger button
enable_button: 10
enable_turbo_button: 8
