robot_base_frame: base_link

transform_tolerance: 0.5

robot_radius: 0.30
inflater:
  robot_radius: 0.30
  inflation_radius: 0.50

obstacles:
  observation_sources: base_scan # head_xtion
  enabled:              true
  max_obstacle_height: 2.0
  obstacle_range: 2.5
  combination_method: 1

  base_scan:
    data_type: LaserScan
    topic: hsrb/base_scan
    marking: true
    clearing: true
    obstacle_range: 6.0
    raytrace_range: 10.0
    min_obstacle_height: 0.1
    max_obstacle_height: 0.3

  # head_xtion:
  #   data_type: PointCloud2
  #   topic: hsrb/head_rgbd_sensor/depth_registered/rectified_points
  #   marking: true
  #   clearing: true
  #   obstacle_range: 6.0
  #   raytrace_range: 10.0
  #   min_obstacle_height: 0.05
  #   max_obstacle_height: 1.0
